jwt:
  secret: secret-1%32Turkiye!An!@$ISTas2#%SDT
server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
    password: Dayan!@2000Qayumi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
