jwt:
  secret: secret-1%32Turkiye!An!@$ISTas2#%SDT
server:
  port: 5000
#  port: 8080
spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/supportportal
    #    username: root
    #    password: Dayan!@2000Qayumi
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
    password: Dayan!@2000Qayumi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
